### ISSUE TITLE
.js socket error starting qps-client in docker container

### ISSUE THREAD

**Issue by twobombs** [quantastica/qps-client#5]
Whilst integrating qps-client into the thereminq controller [image](https://github.com/twobombs/thereminq-tensors/commit/112cd7cffa1129147e06e96d64cd66fd89466651) i found that node throws a socket error when starting qps-client inside the contrainer. I suspect this is because .js cannot open the socket, or does this point to something else ?

<img width="926" alt="Screenshot 2022-01-16 at 11 09 15" src="https://user-images.githubusercontent.com/12692227/149655615-d3667412-cb87-468a-b2bf-53fd790d1a6e.png">

**Comment by perak** [comment]
Can you share the command which you use to start qps-client?

**Comment by perak** [comment]
Note that qps-client is using websocket to connect to QPS, so it is required port 443 to be open (from inside container to the internet)

**Comment by twobombs** [comment]
Thank you for your reply. The command was 

> qps-client


and enter the credentials on the command prompt

i work around this by entering the credentials in the command, but that is something that cannot be put into a repository. I understand that the error has to do with not being able to connect to the remote host instead of opening a local socketed port. I think that is all I need to know for now. Thank you.

**Comment by perak** [comment]
OK. BTW, you can enter credentials automatically by calling qps-client with command line arguments. See `qps-client -h`

**Comment by perak** [comment]
Ah, you are already doing that, I understand now.

**Comment by perak** [comment]
I guess you know it, but just for future readers of this issue: you can pass credentials to docker build via enviroment variables when building your docker image, and inside Dockerfile call `qps-client —password YOUR_ENV_VAR_WITH_PASS —user YOUR_ENV_VAR_WITH_USER_NAME`
